services:
    minio:
        image: 'quay.io/minio/minio:latest'
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - '~/minio/data:/data/minio'
        command: 'minio server /data/minio --console-address ":9001"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s
volumes:
    minio:
        driver: local